apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kepler
  template:
    metadata:
      labels:
        app: kepler
    spec:
      containers:
        - name: kepler-container
          image: kepler:latest
          ports:
            - containerPort: 8080